# Goal - Predict hosptal readmission

A clean way to organize it is:
1. Univariate, non-visual
   - shape, dtypes
   - info
   - missingness
   - duplicates
   - describe()
   - value_counts()
   - cardinality
   - distributions summarized numerically
2. Bivariate, non-visual
   - each predictor vs target
   - groupby() rates like we’ve been doing
   - correlations for numeric variables
   - crosstabs
   - maybe simple statistical tests later
3. Univariate / bivariate visual
   - histograms
   - boxplots
   - count plots
   - bar charts of readmission rate
   - numeric feature vs readmission plots
4. Multivariate, non-visual
   - correlation matrix
   - grouped/cross-tab analyses involving multiple predictors
   - interactions like number_inpatient × age
   - perhaps pivot tables
   - checking whether an apparent bivariate relationship persists after stratifying on another variable
5. Multivariate visual
   - heatmaps
   - scatterplots with hue
   - grouped/stacked bars
   - interaction plots
   - maybe pairplots selectively, not on 50 columns
   
And then you transition into feature selection/engineering → preprocessing → modeling.

In [ ]:
1. Data Overview & Cleaning
2. Univariate Non-Visual EDA
3. Bivariate Non-Visual EDA
4. Univariate/Bivariate Visual EDA
5. Multivariate EDA
6. Feature Engineering
7. Modeling

In [ ]:
# 1. Data Loading and Initial Inspection

# 2. Data Cleaning

# 3. Univariate Non-Visual EDA

# 4. Bivariate Non-Visual EDA

# 5. Visual EDA

# 6. Multivariate EDA

# 7. Feature Engineering

# 8. Modeling

## 1. Data Loading and Cleaning

In [ ]:
import os
import numpy as np
import pandas as pd

os.listdir()

['.git', '.gitignore', '.venv', '01_eda.ipynb', 'data', 'readmission_eda.html']

In [ ]:

data_path = 'C:/Users/dave_/Desktop/projects/hospital readmission/data/'
data_file = 'diabetic_data.csv'
df = pd.read_csv(data_path + data_file)

In [ ]:
df.shape

(101766, 50)

In [ ]:
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101766 non-null  int64
 1   patient_nbr               101766 non-null  int64
 2   race                      101766 non-null  object
 3   gender                    101766 non-null  object
 4   age                       101766 non-null  object
 5   weight                    101766 non-null  object
 6   admission_type_id         101766 non-null  int64
 7   discharge_disposition_id  101766 non-null  int64
 8   admission_source_id       101766 non-null  int64
 9   time_in_hospital          101766 non-null  int64
 10  payer_code                101766 non-null  object
 11  medical_specialty         101766 non-null  object
 12  num_lab_procedures        101766 non-null  int64
 13  num_procedures            101766 non-null  int64
 14  num_medications           101766 non-null  int64
 15  number_outpatient         101766 non-null  int64
 16  number_emergency          101766 non-null  int64
 17  number_inpatient          101766 non-null  int64
 18  diag_1                    101766 non-null  object
 19  diag_2                    101766 non-null  object
 20  diag_3                    101766 non-null  object
 21  number_diagnoses          101766 non-null  int64
 22  max_glu_serum             5346 non-null    object
 23  A1Cresult                 17018 non-null   object
 24  metformin                 101766 non-null  object
 25  repaglinide               101766 non-null  object
 26  nateglinide               101766 non-null  object
 27  chlorpropamide            101766 non-null  object
 28  glimepiride               101766 non-null  object
 29  acetohexamide             101766 non-null  object
 30  glipizide                 101766 non-null  object
 31  glyburide                 101766 non-null  object
 32  tolbutamide               101766 non-null  object
 33  pioglitazone              101766 non-null  object
 34  rosiglitazone             101766 non-null  object
 35  acarbose                  101766 non-null  object
 36  miglitol                  101766 non-null  object
 37  troglitazone              101766 non-null  object
 38  tolazamide                101766 non-null  object
 39  examide                   101766 non-null  object
 40  citoglipton               101766 non-null  object
 41  insulin                   101766 non-null  object
 42  glyburide-metformin       101766 non-null  object
 43  glipizide-metformin       101766 non-null  object
 44  glimepiride-pioglitazone  101766 non-null  object
 45  metformin-rosiglitazone   101766 non-null  object
 46  metformin-pioglitazone    101766 non-null  object
 47  change                    101766 non-null  object
 48  diabetesMed               101766 non-null  object
 49  readmitted                101766 non-null  object
dtypes: int64(13), object(37)
memory usage: 38.8+ MB

In [ ]:
df.describe()

,encounter_id,patient_nbr,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses
count,1.017660e+05,1.017660e+05,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000
mean,1.652016e+08,5.433040e+07,2.024006,3.715642,5.754437,4.395987,43.095641,1.339730,16.021844,0.369357,0.197836,0.635566,7.422607
std,1.026403e+08,3.869636e+07,1.445403,5.280166,4.064081,2.985108,19.674362,1.705807,8.127566,1.267265,0.930472,1.262863,1.933600
min,1.252200e+04,1.350000e+02,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,8.496119e+07,2.341322e+07,1.000000,1.000000,1.000000,2.000000,31.000000,0.000000,10.000000,0.000000,0.000000,0.000000,6.000000
50%,1.523890e+08,4.550514e+07,1.000000,1.000000,7.000000,4.000000,44.000000,1.000000,15.000000,0.000000,0.000000,0.000000,8.000000
75%,2.302709e+08,8.754595e+07,3.000000,4.000000,7.000000,6.000000,57.000000,2.000000,20.000000,0.000000,0.000000,1.000000,9.000000
max,4.438672e+08,1.895026e+08,8.000000,28.000000,25.000000,14.000000,132.000000,6.000000,81.000000,42.000000,76.000000,21.000000,16.000000

In [2]:
df.dtypes

NameError: name 'df' is not defined

In [ ]:
df['readmitted'].value_counts()

readmitted
NO     54864
>30    35545
<30    11357
Name: count, dtype: int64

In [ ]:
df['readmitted'].value_counts(normalize=True)

readmitted
NO     0.539119
>30    0.349282
<30    0.111599
Name: proportion, dtype: float64

In [ ]:
print(df.isnull().sum())

encounter_id                    0
patient_nbr                     0
race                            0
gender                          0
age                             0
weight                          0
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                      0
medical_specialty               0
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                          0
diag_2                          0
diag_3                          0
number_diagnoses                0
max_glu_serum               96420
A1Cresult                   84748
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

In [ ]:
(df == "?").sum().sort_values(ascending=False)

weight                      98569
medical_specialty           49949
payer_code                  40256
race                         2273
diag_3                       1423
diag_2                        358
diag_1                         21
admission_type_id               0
patient_nbr                     0
encounter_id                    0
time_in_hospital                0
admission_source_id             0
num_lab_procedures              0
num_procedures                  0
num_medications                 0
discharge_disposition_id        0
gender                          0
age                             0
number_inpatient                0
number_emergency                0
number_outpatient               0
number_diagnoses                0
max_glu_serum                   0
A1Cresult                       0
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

In [ ]:
df = df.replace('?', np.nan)

In [ ]:
df.isna().sum().sort_values(ascending=False)

weight                      98569
max_glu_serum               96420
A1Cresult                   84748
medical_specialty           49949
payer_code                  40256
race                         2273
diag_3                       1423
diag_2                        358
diag_1                         21
patient_nbr                     0
encounter_id                    0
time_in_hospital                0
admission_source_id             0
num_procedures                  0
num_lab_procedures              0
admission_type_id               0
discharge_disposition_id        0
age                             0
gender                          0
number_inpatient                0
number_emergency                0
number_outpatient               0
num_medications                 0
number_diagnoses                0
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
readmitted_30d                  0
dtype: int64

### Create target variable

In [ ]:
df['readmitted_30d'] = (df['readmitted'] == "<30").astype(int)

## 3. Univariate Non-Visual EDA

In [ ]:
df.age.value_counts().sort_index()

age
[0-10)        161
[10-20)       691
[20-30)      1657
[30-40)      3775
[40-50)      9685
[50-60)     17256
[60-70)     22483
[70-80)     26068
[80-90)     17197
[90-100)     2793
Name: count, dtype: int64

In [ ]:
display(df['readmitted_30d'].value_counts())
display(df['readmitted_30d'].value_counts(normalize=True))

readmitted_30d
0    90409
1    11357
Name: count, dtype: int64

readmitted_30d
0    0.888401
1    0.111599
Name: proportion, dtype: float64

In [ ]:
df.groupby('age')['readmitted_30d'].mean() * 100

age
[0-10)       1.863354
[10-20)      5.788712
[20-30)     14.242607
[30-40)     11.231788
[40-50)     10.604027
[50-60)      9.666203
[60-70)     11.128408
[70-80)     11.773055
[80-90)     12.083503
[90-100)    11.099177
Name: readmitted_30d, dtype: float64

In [ ]:
df.groupby('gender')['readmitted_30d'].mean() * 100

gender
Female             11.245156
Male               11.061524
Unknown/Invalid     0.000000
Name: readmitted_30d, dtype: float64

In [ ]:
df.groupby('time_in_hospital')['readmitted_30d'].mean() * 100

time_in_hospital
1      8.178491
2      9.939619
3     10.666817
4     11.806952
5     12.030905
6     12.587876
7     12.834955
8     14.233660
9     13.724184
10    14.346712
11    10.512129
12    13.328729
13    12.314050
14    12.955854
Name: readmitted_30d, dtype: float64

In [ ]:
df.groupby('number_inpatient')['readmitted_30d'].mean() * 100

number_inpatient
0       8.437084
1      12.924543
2      17.433254
3      20.287306
4      23.612824
5      31.403941
6      34.583333
7      35.447761
8      44.370861
9      42.342342
10     42.622951
11     67.346939
12     50.000000
13     50.000000
14     40.000000
15    100.000000
16     33.333333
17    100.000000
18      0.000000
19     50.000000
21    100.000000
Name: readmitted_30d, dtype: float64

In [ ]:
summary = df.groupby('number_inpatient')['readmitted_30d'].agg(['mean', 'count'])
summary['mean'] = summary['mean'] * 100
summary = summary.sort_values('mean',ascending=True)
summary

                        mean  count
number_inpatient
18                  0.000000      1
0                   8.437084  67630
1                  12.924543  19521
2                  17.433254   7566
3                  20.287306   3411
4                  23.612824   1622
5                  31.403941    812
16                 33.333333      6
6                  34.583333    480
7                  35.447761    268
14                 40.000000     10
9                  42.342342    111
10                 42.622951     61
8                  44.370861    151
13                 50.000000     20
12                 50.000000     34
19                 50.000000      2
11                 67.346939     49
15                100.000000      9
17                100.000000      1
21                100.000000      1

In [ ]:
summary = df.groupby('age')['readmitted_30d'].agg(['mean','count'])
summary['mean'] = summary['mean'] * 100
summary

               mean  count
age
[0-10)     1.863354    161
[10-20)    5.788712    691
[20-30)   14.242607   1657
[30-40)   11.231788   3775
[40-50)   10.604027   9685
[50-60)    9.666203  17256
[60-70)   11.128408  22483
[70-80)   11.773055  26068
[80-90)   12.083503  17197
[90-100)  11.099177   2793

In [ ]:
var_list = ['time_in_hospital', 'number_emergency', 'number_outpatient', 'number_diagnoses']
for var in var_list:
    print(f'\n### {var}')
    summary = df.groupby(var)['readmitted_30d'].agg(['mean','count'])
    summary['mean'] = summary['mean'] * 100
    display(summary)

### time_in_hospital

                       mean  count
time_in_hospital
1                  8.178491  14208
2                  9.939619  17224
3                 10.666817  17756
4                 11.806952  13924
5                 12.030905   9966
6                 12.587876   7539
7                 12.834955   5859
8                 14.233660   4391
9                 13.724184   3002
10                14.346712   2342
11                10.512129   1855
12                13.328729   1448
13                12.314050   1210
14                12.955854   1042

### number_emergency

                        mean  count
number_emergency
0                  10.474315  90383
1                  14.354566   7677
2                  18.266405   2042
3                  20.275862    725
4                  30.748663    374
5                  24.479167    192
6                  23.404255     94
7                  26.027397     73
8                  32.000000     50
9                  36.363636     33
10                 35.294118     34
11                 21.739130     23
12                 20.000000     10
13                 33.333333     12
14                  0.000000      3
15                 33.333333      3
16                 40.000000      5
18                 20.000000      5
19                 50.000000      4
20                 50.000000      4
21                 50.000000      2
22                 50.000000      6
24                  0.000000      1
25                  0.000000      2
28                100.000000      1
29                  0.000000      1
37                  0.000000      1
42                  0.000000      1
46                  0.000000      1
54                  0.000000      1
63                  0.000000      1
64                100.000000      1
76                  0.000000      1

### number_outpatient

                         mean  count
number_outpatient
0                   10.674256  85027
1                   13.923014   8547
2                   13.745131   3594
3                   12.291871   2042
4                   15.104641   1099
5                   11.819887    533
6                   13.201320    303
7                   15.483871    155
8                    5.102041     98
9                   15.662651     83
10                   8.771930     57
11                  14.285714     42
12                  20.000000     30
13                  19.354839     31
14                  17.857143     28
15                  10.000000     20
16                   0.000000     15
17                  12.500000      8
18                   0.000000      5
19                  33.333333      3
20                   0.000000      7
21                   0.000000      7
22                  20.000000      5
23                  50.000000      2
24                   0.000000      3
25                   0.000000      2
26                   0.000000      2
27                   0.000000      3
28                   0.000000      1
29                   0.000000      2
33                   0.000000      2
34                   0.000000      1
35                   0.000000      2
36                   0.000000      2
37                   0.000000      1
38                   0.000000      1
39                   0.000000      1
40                 100.000000      1
42                   0.000000      1

### number_diagnoses

                       mean  count
number_diagnoses
1                  5.936073    219
2                  6.060606   1023
3                  7.372134   2835
4                  8.253567   5537
5                  9.154744  11393
6                 10.412361  10161
7                 10.766862  10393
8                 11.812359  10616
9                 12.380240  49474
10                17.647059     17
11                27.272727     11
12                11.111111      9
13                18.750000     16
14                14.285714      7
15                20.000000     10
16                 8.888889     45

In [ ]:
cat_vars = [
    'admission_type_id',
    'discharge_disposition_id',
    'admission_source_id',
    'race',
    'gender'    
]

for var in cat_vars:
    print(f'\n### {var}')
    summary = (
        df.groupby(var)['readmitted_30d']
        .agg(['mean', 'count'])
    )
    summary['mean'] = summary['mean'] * 100
    display(summary)

### admission_type_id

                        mean  count
admission_type_id
1                  11.522504  53990
2                  11.179654  18480
3                  10.392708  18869
4                  10.000000     10
5                  10.344828   4785
6                  11.075411   5291
7                   0.000000     21
8                   8.437500    320

### discharge_disposition_id

                               mean  count
discharge_disposition_id
1                          9.300395  60234
2                         16.071429   2128
3                         14.662462  13954
4                         12.760736    815
5                         20.861486   1184
6                         12.695706  12902
7                         14.446228    623
8                         13.888889    108
9                         42.857143     21
10                         0.000000      6
11                         0.000000   1642
12                        66.666667      3
13                         4.761905    399
14                         6.451613    372
15                        44.444444     63
16                         0.000000     11
17                         0.000000     14
18                        12.435654   3691
19                         0.000000      8
20                         0.000000      2
22                        27.696939   1993
23                         7.281553    412
24                        14.583333     48
25                         9.302326    989
27                         0.000000      5
28                        36.690647    139

### admission_source_id

                          mean  count
admission_source_id
1                    10.586843  29565
2                    10.054348   1104
3                    15.508021    187
4                     9.695639   3187
5                    11.812865    855
6                     9.363958   2264
7                    11.688176  57494
8                    12.500000     16
9                    10.400000    125
10                    0.000000      8
11                    0.000000      2
13                    0.000000      1
14                    0.000000      2
17                   10.411444   6781
20                   13.664596    161
22                   16.666667     12
25                    0.000000      2

### race

                      mean  count
race
AfricanAmerican  11.218116  19210
Asian            10.140406    641
Caucasian        11.290556  76099
Hispanic         10.407462   2037
Other             9.628154   1506

### gender

                      mean  count
gender
Female           11.245156  54708
Male             11.061524  47055
Unknown/Invalid   0.000000      3

In [ ]:
mapping = pd.read_csv('data/IDS_mapping.csv')
mapping

   admission_type_id                                        description
0                  1                                          Emergency
1                  2                                             Urgent
2                  3                                           Elective
3                  4                                            Newborn
4                  5                                      Not Available
..               ...                                                ...
62                22   Transfer from hospital inpt/same fac reslt in...
63                23                          Born inside this hospital
64                24                         Born outside this hospital
65                25            Transfer from Ambulatory Surgery Center
66                26                              Transfer from Hospice

[67 rows x 2 columns]

In [ ]:
mapping.iloc[39]

admission_type_id                                                   29
description          Discharged/transferred to a Critical Access Ho...
Name: 39, dtype: object

In [ ]:
admission_type_map = dict(
    zip(
        mapping.loc[0:7, 'admission_type_id'].astype(int),
        mapping.loc[0:7, 'description']
    )
)
admission_type_map

{1: 'Emergency',
 2: 'Urgent',
 3: 'Elective',
 4: 'Newborn',
 5: 'Not Available',
 6: nan,
 7: 'Trauma Center',
 8: 'Not Mapped'}

In [ ]:
df['admission_type'] = df['admission_type_id'].map(admission_type_map)

In [ ]:
df.groupby('admission_type')['readmitted_30d'].agg(['mean', 'count'])

                    mean  count
admission_type
Elective        0.103927  18869
Emergency       0.115225  53990
Newborn         0.100000     10
Not Available   0.103448   4785
Not Mapped      0.084375    320
Trauma Center   0.000000     21
Urgent          0.111797  18480

In [ ]:
mapping.iloc[9:40]

,admission_type_id,description
9,discharge_disposition_id,description
10,1,Discharged to home
11,2,Discharged/transferred to another short term h...
12,3,Discharged/transferred to SNF
13,4,Discharged/transferred to ICF
14,5,Discharged/transferred to another type of inpa...
15,6,Discharged/transferred to home with home healt...
16,7,Left AMA
17,8,Discharged/transferred to home under care of H...
18,9,Admitted as an inpatient to this hospital
19,10,Neonate discharged to another hospital for neo...
20,11,Expired
21,12,Still patient or expected to return for outpat...
22,13,Hospice / home
23,14,Hospice / medical facility
24,15,Discharged/transferred within this institution...
25,16,Discharged/transferred/referred another instit...
26,17,Discharged/transferred/referred to this instit...
27,18,NaN
28,19,"Expired at home. Medicaid only, hospice."
29,20,"Expired in a medical facility. Medicaid only, ..."
30,21,"Expired, place unknown. Medicaid only, hospice."
31,22,Discharged/transferred to another rehab fac in...
32,23,Discharged/transferred to a long term care hos...
33,24,Discharged/transferred to a nursing facility c...
34,25,Not Mapped
35,26,Unknown/Invalid
36,30,Discharged/transferred to another Type of Heal...
37,27,Discharged/transferred to a federal health car...
38,28,Discharged/transferred/referred to a psychiatr...
39,29,Discharged/transferred to a Critical Access Ho...

In [ ]:
discharge_map = dict(
    zip(
        mapping.loc[10:39, "admission_type_id"].astype(int),
        mapping.loc[10:39, "description"]
    )
)

In [ ]:
df['discharge_disposition'] = df['discharge_disposition_id'].map(discharge_map)

In [ ]:
admission_source_map = dict(
    zip(
        mapping.loc[42:49, "admission_type_id"].astype(int),
        mapping.loc[42:49, "description"]
    )
)

In [ ]:
df['admission_source'] = df['admission_source_id'].map(admission_source_map)

In [ ]:
cat_vars = [
    "admission_type",
    "discharge_disposition",
    "admission_source",
    "race",
    "gender"
]

for var in cat_vars:
    print(f'\n### {var}')
    summary = (
        df.groupby(var)['readmitted_30d']
        .agg(['mean', 'count'])
        .sort_values('mean', ascending=False)
    )
    summary['mean'] = summary['mean'] * 100
    display(summary)

### admission_type

                     mean  count
admission_type
Emergency       11.522504  53990
Urgent          11.179654  18480
Elective        10.392708  18869
Not Available   10.344828   4785
Newborn         10.000000     10
Not Mapped       8.437500    320
Trauma Center    0.000000     21

### discharge_disposition

                                                         mean  count
discharge_disposition
Still patient or expected to return for outpati...  66.666667      3
Discharged/transferred within this institution ...  44.444444     63
Admitted as an inpatient to this hospital           42.857143     21
Discharged/transferred/referred to a psychiatri...  36.690647    139
Discharged/transferred to another rehab fac inc...  27.696939   1993
Discharged/transferred to another type of inpat...  20.861486   1184
Discharged/transferred to another short term ho...  16.071429   2128
Discharged/transferred to SNF                       14.662462  13954
Discharged/transferred to a nursing facility ce...  14.583333     48
Left AMA                                            14.446228    623
Discharged/transferred to home under care of Ho...  13.888889    108
Discharged/transferred to ICF                       12.760736    815
Discharged/transferred to home with home health...  12.695706  12902
Not Mapped                                           9.302326    989
Discharged to home                                   9.300395  60234
Discharged/transferred to a long term care hosp...   7.281553    412
Hospice / medical facility                           6.451613    372
Hospice / home                                       4.761905    399
Discharged/transferred to a federal health care...   0.000000      5
Discharged/transferred/referred another institu...   0.000000     11
Discharged/transferred/referred to this institu...   0.000000     14
Expired                                              0.000000   1642
Expired in a medical facility. Medicaid only, h...   0.000000      2
Expired at home. Medicaid only, hospice.             0.000000      8
Neonate discharged to another hospital for neon...   0.000000      6

### admission_source

                                                      mean  count
admission_source
HMO Referral                                     15.508021    187
 Court/Law Enforcement                           12.500000     16
 Transfer from a Skilled Nursing Facility (SNF)  11.812865    855
 Emergency Room                                  11.688176  57494
 Physician Referral                              10.586843  29565
Clinic Referral                                  10.054348   1104
Transfer from a hospital                          9.695639   3187
 Transfer from another health care facility       9.363958   2264

### race

                      mean  count
race
Caucasian        11.290556  76099
AfricanAmerican  11.218116  19210
Hispanic         10.407462   2037
Asian            10.140406    641
Other             9.628154   1506

### gender

                      mean  count
gender
Female           11.245156  54708
Male             11.061524  47055
Unknown/Invalid   0.000000      3

In [ ]:
cat_vars_2 = [
    "A1Cresult",
    "max_glu_serum",
    "change",
    "diabetesMed",
    "insulin"
]

for var in cat_vars_2:
    print(f'\n### {var}')
    summary = (
        df.groupby(var)['readmitted_30d']
        .agg(['mean', 'count'])
        .sort_values('mean', ascending=False)
    )
    summary['mean'] = summary['mean'] * 100
    display(summary)

### A1Cresult

                mean  count
A1Cresult
>7         10.047219   3812
>8          9.870983   8216
Norm        9.659319   4990

### max_glu_serum

                    mean  count
max_glu_serum
>300           14.319620   1264
>200           12.457912   1485
Norm           11.359261   2597

### change

             mean  count
change
Ch      11.822765  47011
No      10.590814  54755

### diabetesMed

                  mean  count
diabetesMed
Yes          11.626661  78363
No            9.597060  23403

### insulin

              mean  count
insulin
Down     13.897528  12218
Up       12.990456  11316
Steady   11.128400  30849
No       10.037355  47383

In [ ]:
df.groupby('insulin')['readmitted_30d'].agg(['mean', 'count'])

             mean  count
insulin
Down     0.138975  12218
No       0.100374  47383
Steady   0.111284  30849
Up       0.129905  11316

In [ ]:
for diag_code in ['diag_1', 'diag_2', 'diag_3']:
    display(df[diag_code].value_counts().head(20))

diag_1
428      6862
414      6581
786      4016
410      3614
486      3508
427      2766
491      2275
715      2151
682      2042
434      2028
780      2019
996      1967
276      1889
38       1688
250.8    1680
599      1595
584      1520
V57      1207
250.6    1183
518      1115
Name: count, dtype: int64

diag_2
276       6752
428       6662
250       6071
427       5036
401       3736
496       3305
599       3288
403       2823
414       2650
411       2566
250.02    2074
707       1999
585       1871
584       1649
491       1545
250.01    1523
285       1520
780       1491
425       1434
682       1433
Name: count, dtype: int64

diag_3
250       11555
401        8289
276        5175
428        4577
427        3955
414        3664
496        2605
403        2357
585        1992
272        1969
599        1941
V45        1389
250.02     1369
707        1360
780        1334
285        1200
425        1136
250.6      1080
424        1063
584         963
Name: count, dtype: int64

In [ ]:
def diag_group(code):
    if pd.isna(code):
        return "Unknown"

    code = str(code)

    if code.startswith('250'):
        return "Diabetes"

    try:
        num = float(code)

        if 390 <= num <459 or num == 785:
            return "Circulatory"
        elif 460 <= num <= 519 or num == 786:
            return "Respiratory"
        elif 520 <= num <= 579 or num == 787:
            return "Digestive"
        elif 580 <= num <= 629 or num == 788:
            return "Genitourinary"
        elif 710 <= num <= 739: 
            return "Musculoskeltal"
        elif 800 <= num <= 999:
            return "Injury"
        elif 140 <= num <= 239:
            return "Neoplasm" 
        else:
            return "Other"     

    except ValueError:
        return "Other"

In [ ]:
for col in ['diag_1', 'diag_2', 'diag_3']:
    df[f'{col}_group'] = df[col].apply(diag_group)

In [ ]:
for col in ['diag_1_group', 'diag_2_group', 'diag_3_group']:
    print(f'\n### {col}')
    display(df[col].value_counts())

### diag_1_group

diag_1_group
Circulatory       30340
Other             18269
Respiratory       14423
Digestive          9475
Diabetes           8757
Injury             6974
Genitourinary      5117
Musculoskeltal     4957
Neoplasm           3433
Unknown              21
Name: count, dtype: int64

### diag_2_group

diag_2_group
Circulatory       31828
Other             26606
Diabetes          12794
Respiratory       10895
Genitourinary      8376
Digestive          4170
Neoplasm           2547
Injury             2428
Musculoskeltal     1764
Unknown             358
Name: count, dtype: int64

### diag_3_group

diag_3_group
Circulatory       30202
Other             29299
Diabetes          17157
Respiratory        7358
Genitourinary      6680
Digestive          3930
Injury             1946
Musculoskeltal     1915
Neoplasm           1856
Unknown            1423
Name: count, dtype: int64

In [ ]:
for col in ['diag_1_group', 'diag_2_group', 'diag_3_group']:
    print(f'\n###{col}')
    summary = df.groupby(col)['readmitted_30d'].agg(['mean', 'count'])
    summary['mean'] = summary['mean'] * 100
    display(summary.sort_values('mean', ascending=False))

###diag_1_group

                     mean  count
diag_1_group
Unknown         23.809524     21
Diabetes        12.983899   8757
Injury          12.245483   6974
Other           11.462040  18269
Circulatory     11.460119  30340
Genitourinary   10.846199   5117
Digestive       10.712401   9475
Neoplasm        10.078648   3433
Respiratory      9.727519  14423
Musculoskeltal   9.501715   4957

###diag_2_group

                     mean  count
diag_2_group
Neoplasm        14.919513   2547
Genitourinary   11.759790   8376
Digestive       11.486811   4170
Injury          11.449753   2428
Other           11.253101  26606
Circulatory     11.106573  31828
Diabetes        10.583086  12794
Respiratory     10.518587  10895
Musculoskeltal  10.034014   1764
Unknown          8.100559    358

###diag_3_group

                     mean  count
diag_3_group
Neoplasm        14.224138   1856
Genitourinary   13.458084   6680
Respiratory     12.054906   7358
Digestive       11.959288   3930
Injury          11.562179   1946
Other           11.065224  29299
Circulatory     10.800609  30202
Musculoskeltal  10.652742   1915
Diabetes        10.567115  17157
Unknown          6.394940   1423

So far, our strongest candidates appear to be:
- number_inpatient
- number_emergency
- time_in_hospital
- number_diagnoses
- discharge_disposition
- insulin status
- diagnosis groups